apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: s7ny4sm9r-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:1da7e57f1a042220eb48e878f98aa4cafa013654@sha256:bf72c274b160e6aedd36e107b23d9ef790c705bb24fa768d42671f889490ca7b
          name: container-image
