apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: s7ny4sm9r-python
  janus-idp.io/tekton: s7ny4sm9r-python
  backstage.io/kubernetes-id: s7ny4sm9r-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s7ny4sm9r-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
